// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDI7q3SirOJCN3YMFExqdI5vPMES4taE',
    appId: '1:755856210299:web:925c8625db0e82a63165de',
    messagingSenderId: '755856210299',
    projectId: 'oummi-5f68a',
    authDomain: 'oummi-5f68a.firebaseapp.com',
    storageBucket: 'oummi-5f68a.firebasestorage.app',
    measurementId: 'G-9Y0Q23ZJGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa6igxR8EQ2tKe610o8w4-JXvyWfbDmCQ',
    appId: '1:755856210299:android:53cbf91f7bbc830b3165de',
    messagingSenderId: '755856210299',
    projectId: 'oummi-5f68a',
    storageBucket: 'oummi-5f68a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlug9dBCemB1hHPzsYHVVL0HJRAdfjThc',
    appId: '1:755856210299:ios:9fae87178f42afd83165de',
    messagingSenderId: '755856210299',
    projectId: 'oummi-5f68a',
    storageBucket: 'oummi-5f68a.firebasestorage.app',
    iosBundleId: 'com.example.oummi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlug9dBCemB1hHPzsYHVVL0HJRAdfjThc',
    appId: '1:755856210299:ios:9fae87178f42afd83165de',
    messagingSenderId: '755856210299',
    projectId: 'oummi-5f68a',
    storageBucket: 'oummi-5f68a.firebasestorage.app',
    iosBundleId: 'com.example.oummi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmDI7q3SirOJCN3YMFExqdI5vPMES4taE',
    appId: '1:755856210299:web:8e8bff8b6421fd973165de',
    messagingSenderId: '755856210299',
    projectId: 'oummi-5f68a',
    authDomain: 'oummi-5f68a.firebaseapp.com',
    storageBucket: 'oummi-5f68a.firebasestorage.app',
    measurementId: 'G-XV4MJVBJ0M',
  );
}
